### ISSUE TITLE
Support for Mac OS Ventura ?

### ISSUE THREAD

**Issue by khurshid-alam** [Whisky-App/Whisky#974] opened 2024-05-07 12:13 UTC
### Description

Ventura is only behind Sonoma. Even most premium software packages from Adobe supports Ventura. 

It is weird that Whisky doesn't support Mac OS 13.x

It would be great to have support for Ventura as well.

### Steps to reproduce

None

### Expected behaviour

None

### Logs

```bash
None
```

### What version of Whisky are you using?

<2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by hahayupgit** [comment] 2024-05-07 13:59
Duplicate of #708, GPTK only works with Sonoma

**Closed** 2024-05-07 15:38 UTC
Labels: bug
