### ISSUE TITLE
[Bug]: Whisky crashing

### ISSUE THREAD

**Issue by Guy4456** [Whisky-App/Whisky#474] opened 2023-10-04 07:11 UTC
### Description

I was trying to run a .exe game file on whisky and I noticed a few issues. 1. No audio played when I opened the game 2. when I tried to do anyhting it'd immediately crash. I can't tell if this has anything to do with the bottle I was using. Any way to fix this?

### Steps to reproduce

Run a .exe file with Whisky (the executable for me being [Cursed](url)), no need to use a specific bottle type, any bottle will do fine, then try to enter the game.

### Expected behaviour

I expected the file to open and let me play the game like normal.

### Logs

```bash
Date/Time:        2023-10-02 13:27:41.213 +0300
End time:         2023-10-02 13:28:41.411 +0300
OS Version:       macOS 14.0 (Build 23A344)
Architecture:     arm64e
Report Version:   44
Incident Identifier: 3BEF4B40-C61B-45B2-A139-E42D66D1F8F9

Data Source:      Microstackshots
Shared Cache:     FB8BA21B-013A-3F11-B51E-5D5B4271240D slid base address 0x7ff80c508000, slide 0xc508000
Shared Cache:     7906534C-5D2B-3BA8-B9C6-93A5CF1B7B50 slid base address 0x1826fc000, slide 0x26fc000

Command:          wine64-preloader
Path:             /Users/USER/Library/Application Support/com.isaacmarovitz.Whisky/*/wine64
Resource Coalition ID: 1664
Architecture:     x86_64 (translated)
Parent:           UNKNOWN [1]
PID:              6398

Event:            wakeups
Action taken:     none
Wakeups:          45001 wakeups over the last 60 seconds (748 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:    45000
Limit duration:   300s
Wakeups caused:   45001
Wakeups duration: 60s
Duration:         60.20s
Duration Sampled: 8.01s
Steps:            3

Hardware model:   MacBookAir10,1
Active cpus:      8
HW page size:     16384
VM page size:     16384

Advisory levels:  Battery -> 2, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  59.23 GB/228.27 GB, low space threshold 3072 MB
Low Power Mode:   Enabled
Vnodes Available: 56.74% (68656/121008)

Preferred User Language: en-UG, sw-UG
Country Code:     UG
Keyboards:        ABC
OS Cryptex File Extents: 406

Heaviest stack for the target process:
  3  __wine_syscall_dispatcher_prolog_end + 296 (ntdll.so + 242668) [0x681123ec]
  3  __wine_unix_call + 82 (ntdll.so + 144930) [0x680fa622]
  3  sdl_bus_wait + 82 (winebus.so + 28898) [0x6869d0e2]
  2  SDL_WaitEventTimeout_REAL + 452 (libSDL2-2.0.0.dylib + 141286) [0x6adf57e6]
  2  SDL_Delay_REAL + 83 (libSDL2-2.0.0.dylib + 943615) [0x6aeb95ff]
  2  ??? [0x7ff89d1adbbc]


Powerstats for:   wine64-preloader [6398]
UUID:             29AEEE06-B669-37CF-A7F4-D672222E6D11
Path:             /Users/USER/Library/Application Support/com.isaacmarovitz.Whisky/*/wine64
Shared Cache:     FB8BA21B-013A-3F11-B51E-5D5B4271240D slid base address 0x7ff80c508000, slide 0xc508000
Resource Coalition ID: 1664
Architecture:     x86_64 (translated)
Parent:           UNKNOWN [1]
UID:              502
Footprint:        19.14 MB
Start time:       2023-10-02 13:28:31.471 +0300
End time:         2023-10-02 13:28:39.482 +0300
Num samples:      3 (100%)
Primary state:    2 samples Non-Frontmost App, Non-Suppressed, Kernel mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:    0 samples Idle, 3 samples Active
Power Source:     3 samples on Battery, 0 samples on AC
  3  __wine_syscall_dispatcher_prolog_end + 296 (ntdll.so + 242668) [0x681123ec]
    3  __wine_unix_call + 82 (ntdll.so + 144930) [0x680fa622]
      3  sdl_bus_wait + 82 (winebus.so + 28898) [0x6869d0e2]
        2  SDL_WaitEventTimeout_REAL + 452 (libSDL2-2.0.0.dylib + 141286) [0x6adf57e6]
          2  SDL_Delay_REAL + 83 (libSDL2-2.0.0.dylib + 943615) [0x6aeb95ff]
            2  ??? [0x7ff89d1adbbc]
        1  SDL_WaitEventTimeout_REAL + 462 (libSDL2-2.0.0.dylib + 141296) [0x6adf57f0]
          1  SDL_PumpEventsInternal + 69 (libSDL2-2.0.0.dylib + 140718) [0x6adf55ae]
            1  SDL_JoystickUpdate_REAL + 296 (libSDL2-2.0.0.dylib + 201155) [0x6ae041c3]
              1  DARWIN_JoystickDetect + 69 (libSDL2-2.0.0.dylib + 929310) [0x6aeb5e1e]
                1  CFRunLoopRunSpecific + 374 (CoreFoundation + 502194) [0x7ff80ca1a9b2]
                  1  ??? [0x7ff89cf7852c]
                    1  <User mode>

  Binary Images:
            0x68036000 -         0x68038fff  wine64                                    <29AEEE06-B669-37CF-A7F4-D672222E6D11>  /Users/USER/Library/Application Support/com.isaacmarovitz.Whisky/*/wine64
            0x680d7000 -         0x6819efff  ntdll.so (0)                              <7868059A-8C35-3553-A8D7-63930571CA37>  /Users/USER/Library/Application Support/com.isaacmarovitz.Whisky/*/ntdll.so
            0x68696000 -         0x686a9fff  winebus.so (0)                            <44B81547-69B1-3DD7-BC12-37F59E9309D1>  /Users/USER/Library/Application Support/com.isaacmarovitz.Whisky/*/winebus.so
            0x6add3000 -         0x6aef7fff  libSDL2-2.0.0.dylib (0)                   <440BBADC-484F-3EED-B425-5825CF07AABC>  /Users/USER/Library/Application Support/com.isaacmarovitz.Whisky/*/libSDL2-2.0.0.dylib
        0x7ff80c9a0000 -     0x7ff80ce38ffc  com.apple.CoreFoundation 6.9 (2048.1.403) <C71C408A-6A88-3CD0-AEBF-9012BC196571>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
```

### What version of Whisky are you using?

2.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-10-06 17:24
Duplicate of #452

**Closed by IsaacMarovitz** 2023-10-06 17:24 UTC
Labels: bug
