### ISSUE TITLE
Steam web helper not responding after update

### ISSUE THREAD

**Issue by aSushiLegend** [Whisky-App/Whisky#1200] opened 2024-11-06 16:51 UTC
### Description

The steamwebhelper app isn't responding after the game recording update ![Image](https://github.com/user-attachments/assets/47076491-5d28-49ef-ab60-76ca293069ea)
Even from a fresh install it won't run

### Steps to reproduce

Just install steam and run and after the new update it won't open

### Expected behaviour

Run normally

### Logs

Whisky Version: 2.3.3
Date: 2024-11-06T16:47:06Z
macOS Version: 14.1.1

Bottle Name: 1
Bottle URL: /Users/macbook/Library/Containers/com.isaacmarovitz.Whisky/Bottles/BF44283D-78AD-4D96-B571-76CB2DD1E353

Wine Version: 7.7.0
Windows Version: win11
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/macbook/Downloads/SteamSetup.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/macbook/Library/Containers/com.isaacmarovitz.Whisky/Bottles/BF44283D-78AD-4D96-B571-76CB2DD1E353";
}

msync: bootstrapped mach port on wine-6bf94d0-msync.
msync: up and running.
0170:err:wininet:HTTP_ParseDate unexpected date format L"Mon, 04 Nov 2024 04:25:00 UTC"
01d0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0264:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\gldriverquery.exe" failed, status c0000135
028c:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
028c:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
028c:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
028c:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0294:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0294:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
02c4:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
02d4:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
02d4:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
02e8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
02e8:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
02e8:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0300:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0308:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0310:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0310:err:module:LdrInitializeThunk "chrome_elf.dll" failed to initialize, aborting
0310:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status 80000003
0328:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0330:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0338:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by neighborhoodciv** [comment] 2024-11-06 19:32
Duplicate of https://github.com/Whisky-App/Whisky/issues/1199

**Comment by hahayupgit** [comment] 2024-11-07 03:54
> Duplicate of [#1199](https://github.com/Whisky-App/Whisky/issues/1199)

+1

**Closed by hahayupgit** 2024-11-07 03:54 UTC

**Comment by slawa-c** [comment] 2024-12-10 19:43
me too

**Comment by itskando** [comment] 2025-01-28 17:32
I don't know if this helps:

I only have the issue when macOS display mode is mirroring. (I did not need the downgrade fix.)

If I am using the laptop internal monitor or an external monitor without the internal monitor (clamshell mode — not available when using battery power), I do not have this issue. 

If I am using the laptop internal monitor and plug an external monitor HDMI cable in, steam will even close immediately.
