### ISSUE TITLE
Steamwebhelper not responding with whisky (2.3.3) on m3 pro 16GB ram

### ISSUE THREAD

**Issue by botsbesud** [Whisky-App/Whisky#1201] opened 2024-11-07 00:20 UTC
/## Description

I have re-downloaded steam.exe and whisky (2.3.3) mutiple times with new bottles everytime, different windows versions and even a mac factory reset/data wipe and nothing worked. The problem should be in the whisky code bc the mac version of steam works perfectly fine with no problems at all. (presume its a more widespread issue since theres already 2 reports before mine's for the same  problem)

### Steps to reproduce

Open steam on mac normally via steam.exe

### Expected behaviour

steam works normally

### Logs

Whisky Version: 2.3.3
Date: 2024-11-07T00:13:45Z
macOS Version: 14.6.0

Bottle Name: bottle of water
Bottle URL: /Users/thomaschen/Library/Containers/com.isaacmarovitz.Whisky/Bottles/4C870D72-987D-4956-B5CD-05912CB6AE2C

Wine Version: 7.7.0
Windows Version: win11
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/thomaschen/Library/Containers/com.isaacmarovitz.Whisky/Bottles/4C870D72-987D-4956-B5CD-05912CB6AE2C/drive_c/Program Files (x86)/Steam/steam.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/thomaschen/Library/Containers/com.isaacmarovitz.Whisky/Bottles/4C870D72-987D-4956-B5CD-05912CB6AE2C";
}

msync: bootstrapped mach port on wine-12ec0-msync.
msync: up and running.

### What version of Whisky are you using?

<2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by botsbesud** [comment] 2024-11-07 00:21
Same issue as #1199 and #1200

**Comment by hahayupgit** [comment] 2024-11-07 03:54
Duplicate of #1199

**Closed by hahayupgit** 2024-11-07 03:54 UTC

**Comment by itskando** [comment] 2025-01-28 17:31
I don't know if this helps:

I only have the issue when macOS display mode is mirroring. (I did not need the downgrade fix.)

If I am using the laptop internal monitor or an external monitor without the internal monitor (clamshell mode — not available when using battery power), I do not have this issue. 

If I am using the laptop internal monitor and plug an external monitor HDMI cable in, steam will even close immediately.
