### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IlYAN-FISHERMAN** [Whisky-App/Whisky#729] opened 2023-12-24 15:28 UTC
### Description

since update 2.2.2 nothing works correctly anymore...
genshin impact no longer wants to launch...

### Steps to reproduce

install genshin.
make the update.
run genshin

### Expected behaviour

le jeu peut au moins commencer

### Logs

```bash
.
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by CatRaiden** [comment] 2023-12-27 07:11
same to me

**Comment by Musicminion** [comment] 2023-12-27 12:32
Same to me, more detailed info see https://github.com/Whisky-App/Whisky/issues/737

Some people say that mihoyo updated its anti-cheat system, or updated some API, maybe currently it's better to play genshin-impact cloud version?

**Comment by IlYAN-FISHERMAN** [comment] 2023-12-27 16:39
oh...
if it's true it's the end of genshin on mac sillicon, as long as the gaming porting toolkit is not improved or apple makes their equivalent of whishy or crossover

**Comment by IsaacMarovitz** [comment] 2023-12-29 22:39
Duplicate of #718

**Closed by IsaacMarovitz** 2023-12-29 22:39 UTC
Labels: bug
