### ISSUE TITLE
[Bug]:  Steam No Window, Only wine64-preloader

### ISSUE THREAD

**Issue by johnsonhe** [Whisky-App/Whisky#667] opened 2023-12-01 08:02 UTC
### Description

Installed Steam just fine, but when I go to run Steam.exe, nothing happens. I just see a steam icon in dock named "wine64-preloader" that has no display and does nothing.

### Steps to reproduce

followed this guide to install Steam
[https://steamcommunity.com/app/730/discussions/0/3881596897254712215/](https://steamcommunity.com/app/730/discussions/0/3881596897254712215/)

### Expected behaviour

Steam.exe to open and show the steam window

### Logs

```bash
Whisky Version: 2.2.1
Date: 2023-12-01T07:50:50Z
macOS Version: 14.1.2

Bottle Name: cs2
Bottle URL: /Users/johns/Library/Containers/com.isaacmarovitz.Whisky/Bottles/FEDDF59C-C9A1-4042-9A45-FBD32C1E562D

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Users/johns/Library/Containers/com.isaacmarovitz.Whisky/Bottles/FEDDF59C-C9A1-4042-9A45-FBD32C1E562D/drive_c/Program Files (x86)/Steam/GameOverlayUI.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/johns/Library/Containers/com.isaacmarovitz.Whisky/Bottles/FEDDF59C-C9A1-4042-9A45-FBD32C1E562D";
}
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-12-01 15:10
Duplicate of #644

**Closed by IsaacMarovitz** 2023-12-01 15:10 UTC
Labels: bug
