### ISSUE TITLE
[Bug]: fail to launch Genshin Impact 4.3 after game update, is there any possible solution?

### ISSUE THREAD

**Issue by Musicminion** [Whisky-App/Whisky#737] opened 2023-12-27 12:28 UTC
### Description

Hi there! 
It seems that this is a common issue, after genshin impact updated to 4.3, if you try to launch game, the following things shows. 
<img width="781" alt="截屏2023-12-27 20 25 58" src="https://github.com/Whisky-App/Whisky/assets/84625273/8831ef7a-6348-4a9b-b748-62dfc91f5214">

If you try to find out more, the debugger exit automatedly.

### Steps to reproduce

Launch Genshin impact 4.3. 

### Expected behaviour

Successful Launch

### Logs

```bash
<img width="781" alt="截屏2023-12-27 20 25 58" src="https://github.com/Whisky-App/Whisky/assets/84625273/8831ef7a-6348-4a9b-b748-62dfc91f5214">
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Musicminion** [comment] 2023-12-27 12:30
I just want to know if it is still possible to play Genshin impact game in the future? 
It seems that Mihoyo updated it's anti-cheat system or updated its API, so will whiskey support this in the future?

**Comment by ShaoClean** [comment] 2023-12-29 02:46
https://github.com/Whisky-App/Whisky/issues/718

**Comment by IsaacMarovitz** [comment] 2023-12-29 22:31
Duplicate of #718

**Closed by IsaacMarovitz** 2023-12-29 22:31 UTC
Labels: bug
