### ISSUE TITLE
[Bug]: Hoyoplay isnt opening

### ISSUE THREAD

**Issue by shubs123-cloud** [Whisky-App/Whisky#1041] opened 2024-06-22 10:10 UTC
### Description

whenever i open this newly updated hoyoplay i shows as blank, anyone know how to fix it ?

### Steps to reproduce

download whiskey
download hoyoplay and create a bottle
open hoyoplay

### Expected behaviour

the sceern will be blank or nothing will be shown, not even the close tab button

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-06-15T15:44:34Z
macOS Version: 14.5.0

Bottle Name: steam
Bottle URL: /Users/shubhamdhawan/Library/Containers/com.isaacmarovitz.Whisky/Bottles/8E4EB60A-51FB-49CD-A93D-C8D9B816F05C

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/shubhamdhawan/Library/Containers/com.isaacmarovitz.Whisky/Bottles/8E4EB60A-51FB-49CD-A93D-C8D9B816F05C/drive_c/Program Files/Genshin Impact/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/shubhamdhawan/Library/Containers/com.isaacmarovitz.Whisky/Bottles/8E4EB60A-51FB-49CD-A93D-C8D9B816F05C";
}

msync: bootstrapped mach port on wine-d5538c-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2024-06-22 10:49
Duplicate of #1033

**Closed by IsaacMarovitz** 2024-06-22 10:49 UTC
Labels: bug
