### ISSUE TITLE
Cannot Type Japanese in Steam Game

### ISSUE THREAD

**Issue by hmlaa** [Whisky-App/Whisky#319] opened 2023-08-21 21:27 UTC
Hello,

I'm running Whiskey Version 1.1.0 (17), os Sonoma Version 14.0 Beta (23A5312d), Steam is up to date. I'm trying to run a Japanese game, Winning Post 10 2023 that requires typing to begin the game (player name, horse names, etc). In the past when this happened, I'd do the following:

On Steam click on the game in my library -> manage (settings) -> General -> Launch Options -> LANG=ja_JP.UTF-8 %command%. 

However, when I do this now, it says "command not found". How can I enable Japanese locale within Whisky to be able to type full-width Japanese characters within games? 

Thanks so much,
hmlaa

**Comment by IsaacMarovitz** [comment] 2023-08-24 14:26
Likely duplicate of #191

**Closed by IsaacMarovitz** 2023-08-24 14:26 UTC

**Comment by hmlaa** [comment] 2023-08-24 18:12
> Likely duplicate of #191

Hi There,

I apologize for not understanding fully. but how would I implement this fix in my game? I really appreciate you taking the time to read my issue. 

Sincerely,
hmlaa
