### ISSUE TITLE
[Feature]: Macos 13 (Ventura) and Intel Mac Support.

### ISSUE THREAD

**Issue by ThatTechGuyJeremy** [Whisky-App/Whisky#950] opened 2024-04-22 20:45 UTC
### Is your feature request related to a problem?

Bootcamp is buggy and unstable on my machine (Mid 2015 Mac Pro) I don’t have the money to upgrade but i really wanna play windows games on my mac.

### Describe the solution you'd like

Add Intel CPU Support and Macos Ventura Support. (Only 1 macos version down from the one currently supported)

### Anything else?

Please. I am sure I am not the only one who wants this

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2024-04-22 22:18
Duplicate of #949, also no.

**Closed by IsaacMarovitz** 2024-04-22 22:18 UTC
Labels: enhancement
