### ISSUE TITLE
[Bug]: When run "allfonts" command in Winetricks, Terminal reports an error as follows

### ISSUE THREAD

**Issue by DonghanLyu** [Whisky-App/Whisky#686] opened 2023-12-08 05:11 UTC
### Description

Whiskey ver: 2.2.1
Date: Dec. 8, 2023 13:10 (BJT)
Internet: HK

### Steps to reproduce

1. Winetricks
2. allfonts
3. Terminal error

### Expected behaviour

Install non-Latin characters.

### Logs

```bash
Last login: Fri Dec  8 13:06:47 on ttys000
PATH="/Users/computer/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/computer/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/C69FCCD7-B252-4D47-9F50-1A300A44C28B" "/Users/computer/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" allfonts
computer@Roberts-MacBook-Pro ~ % PATH="/Users/computer/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" WINE=wine64 WINEPREFIX="/Users/computer/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/C69FCCD7-B252-4D47-9F50-1A300A44C28B" "/Users/computer/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks" allfonts
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: .
..
.DS_Store
Program Files
Program Files (x86)
ProgramData
users
windows

Registry info:
/Users/computer/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/C69FCCD7-B252-4D47-9F50-1A300A44C28B/system.reg:#arch=win64
/Users/computer/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/C69FCCD7-B252-4D47-9F50-1A300A44C28B/user.reg:#arch=win64
/Users/computer/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/C69FCCD7-B252-4D47-9F50-1A300A44C28B/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine64 cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Omay238** [comment] 2023-12-11 17:32
I am having the same issue.

**Comment by fleytman** [comment] 2023-12-22 11:57
The problem is in the stable version of winetricks, but be fixed in the development branch. You can manually change the file `~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks`.

**Comment by AESA-2012** [comment] 2023-12-24 07:23
I have the same issue.

**Comment by DonghanLyu** [comment] 2023-12-26 08:37
> The problem is in the stable version of winetricks, but be fixed in the development branch. You can manually change the file `~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks`.

Thanks for the workaround. But how? Like replace directly or wait for Whiskey developers to announce updates?

**Comment by fleytman** [comment] 2023-12-26 09:15
In my case, I replaced the file. It would be nice to have a solution from the Whisky team.

**Comment by cailyoung** [comment] 2023-12-28 22:01
Hi @IsaacMarovitz I went on a long journey with this last night; it looks like someone attempted to apply a fix [here](https://github.com/Whisky-App/Whisky/pull/315) but that was rejected.

Then I forked to try to update the `winetricks` script but I don't see it anywhere; I can see that you switched to 'bundled winetricks' back in August but I can't see how it gets packed into the app because the build process is not in this repo, it seems.

Can you please update the bundled winetricks to the latest commit, or at least one that includes [this fix](https://github.com/Winetricks/winetricks/pull/2147)?

**Comment by IsaacMarovitz** [comment] 2023-12-29 22:30
Winetricks is bundled with Whisky's other dependencies and packaged together by WhiskyBuilder. Whenever you reinstall GPTK, it will download the latest version of Winetricks.

**Closed by IsaacMarovitz** 2023-12-29 22:30 UTC
Labels: bug

**Comment by fleytman** [comment] 2024-01-03 07:46
@IsaacMarovitz Why did you close this topic? At the moment the font installation script is not working, which greatly hinders non-English speaking users. The wineskin supplied with GPTK is without a needed fix. Ideally add a mechanism to Whisky to select the version of wineskin or path to the current version. The current workaround of replacing `~/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/winetricks` seems to me not obvious to all users and contains more potential problems.

**Comment by DonghanLyu** [comment] 2024-01-03 08:16
> Winetricks is bundled with Whisky's other dependencies and packaged together by WhiskyBuilder. Whenever you reinstall GPTK, it will download the latest version of Winetricks.

Thanks for your work on Whiskey. But frankly speaking, ignoring an issue never fixes the problem. It only fuels the disappointment of a negative attitude when facing them.

Please fix the issue of mismatched Winetricks with Whiskey in the future schedule. It will be highly appreciated.

Hoping you have a happy and constructive new year.

**Comment by ErnSur** [comment] 2024-05-10 14:04
Still encountering this issue
