### ISSUE TITLE
[Bug]:  can not open genshin impact

### ISSUE THREAD

**Issue by GalaxySciTech** [Whisky-App/Whisky#740] opened 2023-12-28 17:54 UTC
### Description

when i open my game, it pop up a debugger window , and then nothing happen , i already downloaded  all program

### Steps to reproduce

<img width="833" alt="image" src="https://github.com/Whisky-App/Whisky/assets/30950645/6bf4a0ba-56c3-47a6-ab0d-98e84f5fda3d">
<img width="1397" alt="image" src="https://github.com/Whisky-App/Whisky/assets/30950645/8ae90341-539d-4805-932e-e5fd62d18ec2">

### Expected behaviour

i think it need normal open and start

### Logs

```bash
Whisky Version: 2.2.2
Date: 2023-12-28T17:54:17Z
macOS Version: 14.2.1

Bottle Name: win
Bottle URL: /Users/galaxy/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C8D7D894-71C5-479B-8766-AA553A9E4ECA

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/galaxy/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C8D7D894-71C5-479B-8766-AA553A9E4ECA/drive_c/Program Files/Genshin Impact/Genshin Impact Game/YuanShen.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/galaxy/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C8D7D894-71C5-479B-8766-AA553A9E4ECA";
}
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-12-29 22:32
Duplicate of #718

**Closed by IsaacMarovitz** 2023-12-29 22:32 UTC
Labels: bug
