### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LeeActually** [Whisky-App/Whisky#487] opened 2023-10-07 00:24 UTC
### Description

cannot save bottle after creating bottle, Macbook Pro M1 16Gb

### Steps to reproduce

install Whisky, open, install GPTK via whisky, open, create bottle, naming bottle, continue, no bottle saved.

### Expected behaviour

saved bottle, can open .exe application

### Logs

```bash
where is the log located?, im using sonoma
```

### What version of Whisky are you using?

2.0.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by YRychkov** [comment] 2023-10-08 11:11
You can find all your logs with File -> Open Logs Folder

**Comment by LeeActually** [comment] 2023-10-08 16:11
hmmm, aahh i see, so the log from the mac and not the app log? sorry new in Mac 🥲

**Comment by IsaacMarovitz** [comment] 2023-10-10 13:00
Logs can be viewed by pressing `CMD + L` in Whisky. Please check:
- Is Rosetta installed `softwareupdate --install-rosetta`
- If your home folder contains special characters like `.` at the end

**Comment by IsaacMarovitz** [comment] 2023-10-10 13:00
Duplicate of #359

**Closed by IsaacMarovitz** 2023-10-10 13:00 UTC
Labels: bug
