### ISSUE TITLE
[Bug]: Genshin Impact fail to launch (failed to load 'wineusb.sys.so')

### ISSUE THREAD

**Issue by FredB-mine** [Whisky-App/Whisky#673] opened 2023-12-02 04:45 UTC
### Description

Genshin Impact stucks when loading, then quits with error in about a minute.

I'm using macOS Sonoma Beta 14.2 (23C5055b) if that's important.

The log mentions that wine failed to load 'wineusb.sys.so', so maybe wine problem?

### Steps to reproduce

Download Genshin Impact from [here](https://ys-api.mihoyo.com/event/download_porter/link/ys_cn/official/pc_backup53).

Create a bottle with Windows 10, MSync, and open the Retina mode. DXVK off.
 

### Expected behaviour

I expect it to launch without any error.

### Logs

```bash
Whisky Version: 2.2.1
Date: 2023-12-02T04:35:12Z
macOS Version: 14.2.0

Bottle Name: Windows 10 Container
Bottle URL: /Users/alfred/Library/Containers/com.isaacmarovitz.Whisky/Bottles/779D3F81-BADE-4482-9FA0-66739FBB9152

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: true

Arguments: start /unix /Users/alfred/Library/Containers/com.isaacmarovitz.Whisky/Bottles/779D3F81-BADE-4482-9FA0-66739FBB9152/drive_c/Program Files/Genshin Impact/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "METAL_CAPTURE_ENABLED" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/alfred/Library/Containers/com.isaacmarovitz.Whisky/Bottles/779D3F81-BADE-4482-9FA0-66739FBB9152";
}

msync: bootstrapped mach port on wine-2c36e13-msync.
msync: up and running.
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/alfred/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
02e0: thread_get_state failed on Apple Silicon - faking zero debug registers
0358: thread_get_state failed on Apple Silicon - faking zero debug registers
0380: thread_get_state failed on Apple Silicon - faking zero debug registers
0380: thread_get_state failed on Apple Silicon - faking zero debug registers
03c0: thread_get_state failed on Apple Silicon - faking zero debug registers
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
04b0: thread_get_state failed on Apple Silicon - faking zero debug registers
0440: thread_get_state failed on Apple Silicon - faking zero debug registers
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
0444: thread_get_state failed on Apple Silicon - faking zero debug registers
0358: thread_get_state failed on Apple Silicon - faking zero debug registers
021c: thread_get_state failed on Apple Silicon - faking zero debug registers
04d8: thread_get_state failed on Apple Silicon - faking zero debug registers
04c4: thread_get_state failed on Apple Silicon - faking zero debug registers
04b0: thread_get_state failed on Apple Silicon - faking zero debug registers
04bc: thread_get_state failed on Apple Silicon - faking zero debug registers
04b0: thread_get_state failed on Apple Silicon - faking zero debug registers
021c: thread_get_state failed on Apple Silicon - faking zero debug registers
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
2023-12-02 12:36:06.328 wine64-preloader[8243:160797] Metal GPU Frame Capture Enabled
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
0688:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
021c:err:unwind:RtlCaptureStackBackTrace invalid frame 0000000000120178 (0000000000022000-0000000000120000)
04b0: thread_get_state failed on Apple Silicon - faking zero debug registers
0388: thread_get_state failed on Apple Silicon - faking zero debug registers
04c8: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

2.2.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2024-01-01 06:43
Duplicate of #718

**Closed by IsaacMarovitz** 2024-01-01 06:43 UTC
Labels: bug
