### ISSUE TITLE
HoyoPlay Launcher Issue From Whisky (Genshin Impact)

### ISSUE THREAD

**Issue by Nashh11-afk** [Whisky-App/Whisky#1035] opened 2024-06-18 18:17 UTC
### Description

Genshin Impact recently updated its singular-game launcher into a multi-game launcher, sort of like EpicGames, players are now forced to download the multi-game launcher in order to play any of Hoyoverse's 4 games. The launcher is called HoyoPlay. The issue is that when I try to open the launcher after downloading it, the tab is singular and when you move the long "hoyoplay" tab around(because nothing launched and you're angry), it becomes a gray screen. The weird part of this gray screen is that if you spam your mouse on the edges or around the gray screen, it will pop up links that are incorporated in the launcher, making me think the launcher works BUT Whisky faced an issue while installing it and it's something Whisky will have to resolve. 

If you need more information, please comment and I will try my best to reply asap.

Here is an image. 

<img width="1283" alt="Screenshot 2024-06-18 at 11 08 51 AM" src="https://github.com/Whisky-App/Whisky/assets/173112812/28a0a7df-370a-4f12-ae7c-f28102d11a95">

### Steps to reproduce

1) Open genshinimpact.exe file and be redirected to Wine launcher
2) Bottle Genshin Impact and open/follow installation guide
3) Open Genshin Impact Launcher and be forced to download Hoyoplay, be redirected to Hoyoplay download
4) Follow Hoyoplay installation guide 
5) Finish and try to open the launcher

### Expected behaviour

The launcher is supposed to open with no display issues. We should be able to see all buttons and links on the Hoyoplay launcher and navigate through it. 

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-06-17T10:05:45Z
macOS Version: 14.5.0

Bottle Name: Genshin
Bottle URL: /Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8/drive_c/Program Files/HoYoPlay/launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Volumes/Games/GI/B1C472D6-96F9-42E9-8697-7CD3D7E0DCE8";
}

msync: warning: a previous shm file /wine-9d6ee-msync was not properly removed
msync: bootstrapped mach port on wine-9d6ee-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2024-06-18 19:41
Duplicate of #1033

**Closed by IsaacMarovitz** 2024-06-18 19:41 UTC
Labels: bug

**Comment by shubs123-cloud** [comment] 2024-06-19 09:50
yess this is the sam issue im facing, btw how do i check my logs

**Comment by Andrykhno** [comment] 2024-08-26 20:25
I don't really understand how to solve this problem, I have a file with hoyoplay where genshin is already installed and I can run it immediately, but because of the next update I can't download it because I need access to hoyoplay. How to solve this problem with it? And where to insert this code?

**Comment by Narukane** [comment] 2024-09-25 11:04
https://github.com/Whisky-App/Whisky/issues/1033

Workaround for this issue
