### ISSUE TITLE
[Bug]: Can not run Genshin Impact 4.3 on Mac OS 14.2.1 

### ISSUE THREAD

**Issue by enrico-j-yang** [Whisky-App/Whisky#749] opened 2023-12-30 14:19 UTC
### Description

Can not run Genshin Impact 4.3 on Mac OS 14.2.1 
Genshin Impact 4.2 can run on Mac OS 14.2.0

### Steps to reproduce

1. launch launcher.exe
2. launch game

### Expected behaviour

Can run Genshin Impact 4.3

### Logs

```bash
None
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by enrico-j-yang** [comment] 2023-12-30 14:25
<img width="205" alt="image" src="https://github.com/Whisky-App/Whisky/assets/23226706/c61c1999-b5df-4d4a-a8c0-47427b234bfc">

**Comment by AugustRush923** [comment] 2024-01-01 06:13
I have the same question

**Comment by IsaacMarovitz** [comment] 2024-01-01 06:43
Duplicate of #718

**Closed by IsaacMarovitz** 2024-01-01 06:43 UTC
Labels: bug
